<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\EduCore.Domain\EduCore.Domain.csproj" />
		<ProjectReference Include="..\EduCore.Services Abstraction\EduCore.Services Abstraction.csproj" />
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="Hangfire.Core" Version="1.8.23" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="CloudinaryDotNet" Version="1.28.0" />
		<PackageReference Include="RestSharp" Version="110.2.0" />
	</ItemGroup>
	

</Project>
